export const THEMES = [
    {
        id: "custom",
        name: "Custom",
        type: "basic",
        preview: "bg-white border-2 border-dashed border-neutral-300",
        isPro: false,
    },
    {
        id: "air-smoke",
        name: "Air Smoke",
        type: "preset",
        bgType: "color",
        bgColor: "#F3F4F6",
        buttonStyle: "fill",
        buttonColor: "#ffffff",
        buttonFontColor: "#000000",
        fontFamily: "Inter",
        fontColor: "#000000",
        preview: "bg-[#F3F4F6]",
        isPro: true,
    },
    {
        id: "mineral-blue",
        name: "Mineral Blue",
        type: "preset",
        bgType: "color",
        bgColor: "#E0F2FE",
        buttonStyle: "soft",
        buttonColor: "#0EA5E9",
        buttonFontColor: "#0284C7",
        fontFamily: "Inter",
        fontColor: "#0C4A6E",
        preview: "bg-[#E0F2FE]",
        isPro: true,
    },
    {
        id: "mineral-green",
        name: "Mineral Green",
        type: "preset",
        bgType: "color",
        bgColor: "#DCFCE7",
        buttonStyle: "soft",
        buttonColor: "#22C55E",
        buttonFontColor: "#15803D",
        fontFamily: "Inter",
        fontColor: "#14532D",
        preview: "bg-[#DCFCE7]",
        isPro: true,
    },
    // ✨ PREMIUM THEMES
    {
        id: "noir",
        name: "Noir Luxury",
        type: "preset",
        bgType: "color",
        bgColor: "#000000",
        buttonStyle: "outline",
        buttonColor: "#ffffff",
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#ffffff",
        preview: "bg-black",
        isPro: true,
    },
    {
        id: "midnight-blur",
        name: "Midnight Blur",
        type: "preset",
        bgType: "gradient",
        bgGradient: "from-slate-900 via-purple-900 to-slate-900",
        buttonStyle: "fill",
        buttonColor: "rgba(255,255,255,0.1)", // Glassmorphism
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#ffffff",
        preview: "bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900",
        isPro: true,
    },
    {
        id: "sunset-vibes",
        name: "Miami Sunset",
        type: "preset",
        bgType: "gradient",
        bgGradient: "from-orange-400 to-rose-400",
        buttonStyle: "hard-shadow",
        buttonColor: "#FFFBEB",
        buttonFontColor: "#EA580C",
        fontFamily: "DM Sans", 
        fontColor: "#7c2d12",
        preview: "bg-gradient-to-br from-orange-400 to-rose-400",
        isPro: true,
    },
     {
        id: "luxury-gold",
        name: "Luxury Gold",
        type: "preset",
        bgType: "color",
        bgColor: "#0f0f0f",
        buttonStyle: "outline",
        buttonColor: "#D4AF37", // Gold
        buttonFontColor: "#D4AF37",
        fontFamily: "serif",
        fontColor: "#D4AF37",
        preview: "bg-neutral-900 border-2 border-[#D4AF37]",
        isPro: true,
    },
    {
        id: "forest-glass",
        name: "Forest Glass",
        type: "preset",
        bgType: "gradient",
        bgGradient: "from-emerald-900 to-teal-900",
        buttonStyle: "soft",
        buttonColor: "rgba(255,255,255,0.1)", // Glass
        buttonFontColor: "#ffffff",
        fontFamily: "Manrope",
        fontColor: "#A7F3D0",
        preview: "bg-gradient-to-br from-emerald-900 to-teal-900",
        isPro: true,
    },
    {
        id: "deep-space",
        name: "Deep Space",
        type: "preset",
        bgType: "gradient",
        bgGradient: "from-slate-900 via-purple-900 to-indigo-900",
        buttonStyle: "soft",
        buttonColor: "#6366f1",
        buttonFontColor: "#e0e7ff",
        fontFamily: "Inter",
        fontColor: "#ffffff",
        preview: "bg-gradient-to-br from-slate-900 via-purple-900 to-indigo-900",
        isPro: true,
    },
    /* --- NEW GRAPHIC THEMES --- */
    {
        id: "grid-lock",
        name: "Grid Lock",
        type: "preset",
        bgType: "color",
        bgColor: "#ffffff",
        buttonStyle: "hard-shadow",
        buttonColor: "#ffffff",
        buttonFontColor: "#000000",
        fontFamily: "monospace",
        fontColor: "#000000",
        preview: "bg-[url('https://grainy-gradients.vercel.app/noise.svg')] bg-gray-100", // Using a placeholder pattern effect if possible or just color
        isPro: true,
    },
    {
        id: "swiss-minimal",
        name: "Swiss Minimal",
        type: "preset",
        bgType: "color",
        bgColor: "#F5F5F7",
        buttonStyle: "outline",
        buttonColor: "#000000",
        buttonFontColor: "#000000",
        fontFamily: "Inter",
        fontColor: "#000000",
        preview: "bg-[#F5F5F7]",
        isPro: true,
    },
    {
        id: "bubblegum",
        name: "Bubblegum Pop",
        type: "preset",
        bgType: "color",
        bgColor: "#FDF2F8",
        buttonStyle: "shadow",
        buttonColor: "#F472B6",
        buttonFontColor: "#ffffff",
        fontFamily: "Plus Jakarta Sans",
        fontColor: "#831843",
        preview: "bg-[#FDF2F8]",
        isPro: true,
    },
];
