export const THEMES = [
    {
        id: "custom",
        name: "Custom",
        type: "basic",
        preview: "bg-white border-2 border-dashed border-neutral-300",
        bgType: "color",
        bgColor: "#ffffff",
        bgGradient: "from-indigo-500 to-purple-600",
        buttonStyle: "fill",
        buttonRoundness: "xl",
        buttonColor: "#171717",
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#171717",
        isPro: false,
    },
    {
        id: "air-smoke",
        name: "Air Smoke",
        type: "preset",
        bgType: "color",
        bgColor: "#F3F4F6",
        buttonStyle: "fill",
        buttonRoundness: "xl",
        buttonColor: "#ffffff",
        buttonFontColor: "#000000",
        fontFamily: "Inter",
        fontColor: "#000000",
        preview: "bg-[#F3F4F6]",
        isPro: true,
    },
    {
        id: "mineral-blue",
        name: "Mineral Blue",
        type: "preset",
        bgType: "color",
        bgColor: "#E0F2FE",
        buttonStyle: "soft",
        buttonRoundness: "xl",
        buttonColor: "#0EA5E9",
        buttonFontColor: "#0284C7",
        fontFamily: "Inter",
        fontColor: "#0C4A6E",
        preview: "bg-[#E0F2FE]",
        isPro: true,
    },
    {
        id: "mineral-green",
        name: "Mineral Green",
        type: "preset",
        bgType: "color",
        bgColor: "#DCFCE7",
        buttonStyle: "soft",
        buttonRoundness: "xl",
        buttonColor: "#22C55E",
        buttonFontColor: "#15803D",
        fontFamily: "Inter",
        fontColor: "#14532D",
        preview: "bg-[#DCFCE7]",
        isPro: true,
    },
    // ✨ PREMIUM THEMES
    {
        id: "noir",
        name: "Noir Luxury",
        type: "preset",
        bgType: "color",
        bgColor: "#000000",
        buttonStyle: "outline",
        buttonRoundness: "none",
        buttonColor: "#ffffff",
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#ffffff",
        preview: "bg-black",
        isPro: true,
    },
    {
        id: "midnight-blur",
        name: "Midnight Blur",
        type: "preset",
        bgType: "gradient",
        bgGradient: "from-slate-900 via-purple-900 to-slate-900",
        buttonStyle: "fill",
        buttonRoundness: "xl",
        buttonColor: "rgba(255,255,255,0.1)", // Glassmorphism
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#ffffff",
        preview: "bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900",
        isPro: true,
    },
    {
        id: "sunset-vibes",
        name: "Miami Sunset",
        type: "preset",
        bgType: "gradient",
        bgGradient: "from-orange-400 to-rose-400",
        buttonStyle: "hard-shadow",
        buttonRoundness: "none",
        buttonColor: "#FFFBEB",
        buttonFontColor: "#EA580C",
        fontFamily: "DM Sans", 
        fontColor: "#7c2d12",
        preview: "bg-gradient-to-br from-orange-400 to-rose-400",
        isPro: true,
    },
     {
        id: "luxury-gold",
        name: "Luxury Gold",
        type: "preset",
        bgType: "color",
        bgColor: "#0f0f0f",
        buttonStyle: "outline",
        buttonRoundness: "none",
        buttonColor: "#D4AF37", // Gold
        buttonFontColor: "#D4AF37",
        fontFamily: "serif",
        fontColor: "#D4AF37",
        preview: "bg-neutral-900 border-2 border-[#D4AF37]",
        isPro: true,
    },
    {
        id: "forest-glass",
        name: "Forest Glass",
        type: "preset",
        bgType: "gradient",
        bgGradient: "from-emerald-900 to-teal-900",
        buttonStyle: "soft",
        buttonRoundness: "xl",
        buttonColor: "rgba(255,255,255,0.1)", // Glass
        buttonFontColor: "#ffffff",
        fontFamily: "Manrope",
        fontColor: "#A7F3D0",
        preview: "bg-gradient-to-br from-emerald-900 to-teal-900",
        isPro: true,
    },
    {
        id: "deep-space",
        name: "Deep Space",
        type: "preset",
        bgType: "gradient",
        bgGradient: "from-slate-900 via-purple-900 to-indigo-900",
        buttonStyle: "soft",
        buttonRoundness: "full",
        buttonColor: "#6366f1",
        buttonFontColor: "#e0e7ff",
        fontFamily: "Inter",
        fontColor: "#ffffff",
        preview: "bg-gradient-to-br from-slate-900 via-purple-900 to-indigo-900",
        isPro: true,
    },
    /* --- PREMIUM GRAPHIC THEMES --- */
    {
        id: "neon-tokyo",
        name: "Neon Tokyo",
        type: "preset",
        bgType: "gradient",
        bgGradient: "bg-neutral-900 bg-[linear-gradient(to_right,#f0f_1px,transparent_1px),linear-gradient(to_bottom,#0ff_1px,transparent_1px)] bg-[size:4rem_4rem]",
        buttonStyle: "outline",
        buttonRoundness: "none",
        buttonColor: "#0ff",
        buttonFontColor: "#0ff",
        fontFamily: "monospace",
        fontColor: "#f0f",
        preview: "bg-neutral-900 bg-[linear-gradient(to_right,#f0f_1px,transparent_1px),linear-gradient(to_bottom,#0ff_1px,transparent_1px)] bg-[size:2rem_2rem]",
        isPro: true,
    },
    {
        id: "blueprint",
        name: "Blueprint",
        type: "preset",
        bgType: "gradient",
        bgGradient: "bg-[#1e40af] bg-[linear-gradient(#ffffff33_1px,transparent_1px),linear-gradient(90deg,#ffffff33_1px,transparent_1px)] bg-[size:20px_20px]",
        buttonStyle: "outline",
        buttonRoundness: "none",
        buttonColor: "#ffffff",
        buttonFontColor: "#ffffff",
        fontFamily: "monospace",
        fontColor: "#ffffff",
        preview: "bg-[#1e40af] bg-[linear-gradient(#ffffff33_1px,transparent_1px),linear-gradient(90deg,#ffffff33_1px,transparent_1px)] bg-[size:20px_20px]",
        isPro: true,
    },
    {
        id: "soft-serenity",
        name: "Soft Serenity",
        type: "preset",
        bgType: "color",
        bgColor: "#FAFAF9", // Stone 50
        buttonStyle: "soft",
        buttonRoundness: "full",
        buttonColor: "#78716c", // Stone 500
        buttonFontColor: "#ffffff",
        fontFamily: "serif",
        fontColor: "#44403c",
        preview: "bg-[#FAFAF9]",
        isPro: true,
    },
    {
        id: "cyber-grid",
        name: "Cyber Grid",
        type: "preset",
        bgType: "gradient", 
        bgGradient: "bg-neutral-950 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:24px_24px]",
        buttonStyle: "outline",
        buttonRoundness: "none",
        buttonColor: "#00f2ff",
        buttonFontColor: "#00f2ff",
        fontFamily: "monospace",
        fontColor: "#00f2ff",
        preview: "bg-neutral-950 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:24px_24px]", 
        isPro: true,
    },
    {
        id: "mesh-purple",
        name: "Amethyst Mesh",
        type: "preset",
        bgType: "gradient",
        bgGradient: "from-indigo-500 via-purple-500 to-pink-500", 
        buttonStyle: "soft",
        buttonRoundness: "xl",
        buttonColor: "#ffffff",
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#ffffff",
        preview: "bg-gradient-to-br from-indigo-500 via-purple-500 to-pink-500",
        isPro: true,
    },
    {
        id: "abstract-dark",
        name: "Obsidian Waves",
        type: "preset",
        bgType: "image",
        bgImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=2564&auto=format&fit=crop",
        buttonStyle: "fill",
        buttonRoundness: "none",
        buttonColor: "#ffffff",
        buttonFontColor: "#000000",
        fontFamily: "Inter",
        fontColor: "#ffffff",
        preview: "bg-[url('https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=500&auto=format&fit=crop')] bg-cover",
        isPro: true,
    },
     {
        id: "nature-leaves",
        name: "Zen Garden",
        type: "preset",
        bgType: "image",
        bgImage: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?q=80&w=2574&auto=format&fit=crop",
        buttonStyle: "soft",
        buttonRoundness: "full",
        buttonColor: "#ffffff",
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#ffffff",
        preview: "bg-[url('https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?q=80&w=500&auto=format&fit=crop')] bg-cover",
        isPro: true,
    },
    {
        id: "ocean-depths",
        name: "Pacific Depths",
        type: "preset",
        bgType: "image",
        bgImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2670&auto=format&fit=crop",
        buttonStyle: "outline",
        buttonRoundness: "xl",
        buttonColor: "#ffffff",
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#ffffff",
        preview: "bg-[url('https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=500&auto=format&fit=crop')] bg-cover",
        isPro: true,
    },
    /* --- MORE GRAPHIC THEMES --- */
    {
        id: "grid-lock",
        name: "Grid Lock",
        type: "preset",
        bgType: "color",
        bgColor: "#ffffff",
        buttonStyle: "hard-shadow",
        buttonRoundness: "none",
        buttonColor: "#ffffff",
        buttonFontColor: "#000000",
        fontFamily: "monospace",
        fontColor: "#000000",
        preview: "bg-neutral-100", 
        isPro: true,
    },
    {
        id: "swiss-minimal",
        name: "Swiss Minimal",
        type: "preset",
        bgType: "color",
        bgColor: "#F5F5F7",
        buttonStyle: "outline",
        buttonRoundness: "none",
        buttonColor: "#000000",
        buttonFontColor: "#000000",
        fontFamily: "Inter",
        fontColor: "#000000",
        preview: "bg-[#F5F5F7]",
        isPro: true,
    },
    {
        id: "bubblegum",
        name: "Bubblegum Pop",
        type: "preset",
        bgType: "color",
        bgColor: "#FDF2F8",
        buttonStyle: "shadow",
        buttonRoundness: "full",
        buttonColor: "#F472B6",
        buttonFontColor: "#ffffff",
        fontFamily: "Plus Jakarta Sans",
        fontColor: "#831843",
        preview: "bg-[#FDF2F8]",
        isPro: true,
    },
    {
        id: "retro-grid",
        name: "Retro Synth",
        type: "preset",
        bgType: "gradient",
        bgGradient: "bg-slate-900 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:40px_40px]",
        buttonStyle: "hard-shadow",
        buttonRoundness: "none",
        buttonColor: "#F472B6",
        buttonFontColor: "#000000",
        fontFamily: "monospace",
        fontColor: "#ffffff",
        preview: "bg-slate-900 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:40px_40px]",
        isPro: true,
    },
    {
        id: "dot-matrix",
        name: "Dot Matrix",
        type: "preset",
        bgType: "gradient",
        bgGradient: "bg-neutral-950 bg-[radial-gradient(#ffffff33_1px,transparent_1px)] bg-[size:20px_20px]",
        buttonStyle: "outline",
        buttonRoundness: "none",
        buttonColor: "#ffffff",
        buttonFontColor: "#ffffff",
        fontFamily: "monospace",
        fontColor: "#ffffff",
        preview: "bg-neutral-950 bg-[radial-gradient(#ffffff33_1px,transparent_1px)] bg-[size:20px_20px]",
        isPro: true,
    },
    {
        id: "midnight-aurora",
        name: "Midnight Aurora",
        type: "preset",
        bgType: "gradient",
        bgGradient: "bg-gradient-to-t from-gray-900 via-purple-900 to-violet-600",
        buttonStyle: "soft",
        buttonRoundness: "xl",
        buttonColor: "#c084fc",
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#ffffff",
        preview: "bg-gradient-to-t from-gray-900 via-purple-900 to-violet-600",
        isPro: true,
    },
    {
        id: "crimson-tide",
        name: "Crimson Tide",
        type: "preset",
        bgType: "image",
        bgImage: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=2670&auto=format&fit=crop",
        buttonStyle: "fill",
        buttonRoundness: "xl",
        buttonColor: "#ffffff",
        buttonFontColor: "#991b1b",
        fontFamily: "Inter",
        fontColor: "#ffffff",
        preview: "bg-[url('https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=500&auto=format&fit=crop')] bg-cover",
        isPro: true,
    },
];
