export const THEMES = [
    // ============================================
    // 1. MINIMAL (10)
    // ============================================
    {
        id: "custom",
        name: "Custom",
        category: "Minimal", 
        type: "basic",
        preview: "bg-white border-2 border-dashed border-neutral-300",
        bgType: "color",
        bgColor: "#ffffff",
        bgGradient: "",
        buttonStyle: "fill",
        buttonRoundness: "xl",
        buttonColor: "#171717",
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#171717",
        isPro: false,
    },
    {
        id: "clean-white",
        name: "Clean White",
        category: "Minimal",
        type: "preset",
        bgType: "color",
        bgColor: "#ffffff",
        buttonStyle: "outline",
        buttonRoundness: "lg",
        buttonColor: "#000000",
        buttonFontColor: "#000000",
        fontFamily: "Inter",
        fontColor: "#000000",
        preview: "bg-white border border-neutral-200",
        isPro: false,
    },
    {
        id: "clean-black",
        name: "Clean Black",
        category: "Minimal",
        type: "preset",
        bgType: "color",
        bgColor: "#000000",
        buttonStyle: "outline",
        buttonRoundness: "lg",
        buttonColor: "#ffffff",
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#ffffff",
        preview: "bg-black border border-neutral-800",
        isPro: false,
    },
    {
        id: "arctic-grey",
        name: "Arctic Grey",
        category: "Minimal",
        type: "preset",
        bgType: "color",
        bgColor: "#f3f4f6", // gray-100
        buttonStyle: "fill",
        buttonRoundness: "full",
        buttonColor: "#1f2937", // gray-800
        buttonFontColor: "#ffffff",
        fontFamily: "Manrope",
        fontColor: "#1f2937",
        preview: "bg-[#f3f4f6]",
        isPro: false,
    },
    {
        id: "misted-slate",
        name: "Misted Slate",
        category: "Minimal",
        type: "preset",
        bgType: "color",
        bgColor: "#e2e8f0", // slate-200
        buttonStyle: "soft",
        buttonRoundness: "md",
        buttonColor: "#475569", // slate-600
        buttonFontColor: "#f8fafc",
        fontFamily: "Inter",
        fontColor: "#334155",
        preview: "bg-[#e2e8f0]",
        isPro: false,
    },
    {
        id: "soft-sand",
        name: "Soft Sand",
        category: "Minimal",
        type: "preset",
        bgType: "color",
        bgColor: "#f5f5f4", // stone-100
        buttonStyle: "shadow",
        buttonRoundness: "xl",
        buttonColor: "#d6d3d1", // stone-300
        buttonFontColor: "#292524",
        fontFamily: "serif",
        fontColor: "#44403c",
        preview: "bg-[#f5f5f4]",
        isPro: false,
    },
    {
        id: "charcoal-matte",
        name: "Charcoal",
        category: "Minimal",
        type: "preset",
        bgType: "color",
        bgColor: "#262626", // neutral-800
        buttonStyle: "fill",
        buttonRoundness: "none",
        buttonColor: "#404040", // neutral-700
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#e5e5e5",
        preview: "bg-[#262626]",
        isPro: false,
    },
    {
        id: "swiss-design",
        name: "Swiss",
        category: "Minimal",
        type: "preset",
        bgType: "color",
        bgColor: "#ffffff",
        buttonStyle: "hard-shadow",
        buttonRoundness: "none",
        buttonColor: "#ffffff",
        buttonFontColor: "#000000",
        fontFamily: "Inter",
        fontColor: "#000000",
        preview: "bg-white border-2 border-black",
        isPro: false,
    },
    {
        id: "ink-black",
        name: "Ink",
        category: "Minimal",
        type: "preset",
        bgType: "color",
        bgColor: "#0a0a0a",
        buttonStyle: "soft",
        buttonRoundness: "xl",
        buttonColor: "#262626",
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#a3a3a3",
        preview: "bg-[#0a0a0a]",
        isPro: false,
    },
    {
        id: "off-white",
        name: "Off White",
        category: "Minimal",
        type: "preset",
        bgType: "color",
        bgColor: "#fafafa",
        buttonStyle: "fill",
        buttonRoundness: "md",
        buttonColor: "#171717",
        buttonFontColor: "#ffffff",
        fontFamily: "Plus Jakarta Sans",
        fontColor: "#171717",
        preview: "bg-[#fafafa]",
        isPro: false,
    },

    // ============================================
    // 2. ANIMATED (10) - Uses themes.css classes
    // ============================================
    {
        id: "winter-snow",
        name: "Winter Snow",
        category: "Animated",
        isPro: true,
        bgType: "gradient",
        bgGradient: "theme-snow", // CSS Class
        buttonStyle: "soft",
        buttonRoundness: "full",
        buttonColor: "rgba(255,255,255,0.15)",
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#e2e8f0",
        preview: "bg-[#0f172a] theme-snow",
    },
     {
        id: "starry-night",
        name: "Deep Space",
        category: "Animated",
        isPro: true,
        bgType: "gradient",
        bgGradient: "theme-stars", // CSS Class
        buttonStyle: "outline",
        buttonRoundness: "xl",
        buttonColor: "#ffffff",
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#ffffff",
        preview: "bg-black theme-stars",
    },
    {
        id: "aurora-borealis",
        name: "Aurora",
        category: "Animated",
        isPro: true,
        bgType: "gradient",
        bgGradient: "bg-gradient-to-t from-gray-900 via-[#3b0764] to-[#1e1b4b] animate-gradient-y",
        buttonStyle: "soft",
        buttonRoundness: "xl",
        buttonColor: "rgba(255,255,255,0.1)",
        buttonFontColor: "#ffffff",
        fontFamily: "Manrope",
        fontColor: "#ffffff",
        preview: "bg-gradient-to-t from-gray-900 via-[#3b0764] to-[#1e1b4b]",
    },
    {
        id: "holographic",
        name: "Holographic",
        category: "Animated",
        isPro: true,
        bgType: "gradient",
        bgGradient: "bg-gradient-to-r from-[#FF9A9E] via-[#FECFEF] to-[#FF9A9E] animate-gradient-xy",
        buttonStyle: "soft",
        buttonRoundness: "full",
        buttonColor: "rgba(255,255,255,0.6)",
        buttonFontColor: "#be185d",
        fontFamily: "Plus Jakarta Sans",
        fontColor: "#831843",
        preview: "bg-gradient-to-r from-[#FF9A9E] via-[#FECFEF] to-[#FF9A9E]",
    },
     {
        id: "cyber-grid-move",
        name: "Cyber Grid",
        category: "Animated",
        isPro: true,
        bgType: "gradient",
        bgGradient: "theme-grid-move", // CSS Class
        buttonStyle: "outline",
        buttonRoundness: "none",
        buttonColor: "#00ff9d",
        buttonFontColor: "#00ff9d",
        fontFamily: "monospace",
        fontColor: "#00ff9d",
        preview: "bg-black theme-grid-move",
    },
    {
        id: "bokeh-lights",
        name: "Night Lights",
        category: "Animated",
        isPro: true,
        bgType: "gradient",
        bgGradient: "theme-bokeh", // CSS Class
        buttonStyle: "soft",
        buttonRoundness: "xl",
        buttonColor: "rgba(255,255,255,0.1)",
        buttonFontColor: "#e2e8f0",
        fontFamily: "Inter",
        fontColor: "#ffffff",
        preview: "bg-[#1a1a2e]",
    },
    {
        id: "drifting-clouds",
        name: "Sky Drift",
        category: "Animated",
        isPro: true,
        bgType: "gradient",
        bgGradient: "theme-clouds", // CSS Class
        buttonStyle: "fill",
        buttonRoundness: "full",
        buttonColor: "#ffffff",
        buttonFontColor: "#0ea5e9",
        fontFamily: "Inter",
        fontColor: "#0c4a6e",
        preview: "bg-[#38bdf8]",
    },
    {
        id: "disco-fever",
        name: "Disco",
        category: "Animated",
        isPro: true,
        bgType: "gradient",
        bgGradient: "theme-disco",
        buttonStyle: "fill",
        buttonRoundness: "full",
        buttonColor: "black",
        buttonFontColor: "#fff",
        fontFamily: "Plus Jakarta Sans",
        fontColor: "#000",
        preview: "bg-purple-600",
    },
    {
        id: "golden-hour",
        name: "Golden Hour",
        category: "Animated",
        isPro: true,
        bgType: "gradient",
        bgGradient: "bg-gradient-to-br from-[#f59e0b] via-[#ea580c] to-[#b91c1c] animate-gradient-x",
        buttonStyle: "shadow",
        buttonRoundness: "lg",
        buttonColor: "#fff7ed",
        buttonFontColor: "#9a3412",
        fontFamily: "serif",
        fontColor: "#fff7ed",
        preview: "bg-gradient-to-br from-[#f59e0b] via-[#ea580c] to-[#b91c1c]",
    },
    {
        id: "matrix-rain",
        name: "Matrix",
        category: "Animated",
        isPro: true,
        bgType: "gradient",
        bgGradient: "theme-rain", // CSS Class (Lite version)
        buttonStyle: "outline",
        buttonRoundness: "none",
        buttonColor: "#00ff41",
        buttonFontColor: "#00ff41",
        fontFamily: "monospace",
        fontColor: "#00ff41",
        preview: "bg-black theme-rain",
    },

    // ============================================
    // 3. GRAPHICS & PATTERNS (10)
    // ============================================
    {
        id: "blueprint-tech",
        name: "Blueprint",
        category: "Graphics",
        type: "preset",
        bgType: "gradient",
        bgGradient: "bg-[#1e40af] bg-[linear-gradient(#ffffff33_1px,transparent_1px),linear-gradient(90deg,#ffffff33_1px,transparent_1px)] bg-[size:20px_20px]",
        buttonStyle: "outline",
        buttonRoundness: "none",
        buttonColor: "#ffffff",
        buttonFontColor: "#ffffff",
        fontFamily: "monospace",
        fontColor: "#eff6ff",
        preview: "bg-[#1e40af]",
        isPro: true,
    },
    {
        id: "dot-grid-dark",
        name: "Dot Matrix",
        category: "Graphics",
        type: "preset",
        bgType: "gradient",
        bgGradient: "bg-neutral-950 bg-[radial-gradient(#ffffff33_1px,transparent_1px)] bg-[size:20px_20px]",
        buttonStyle: "outline",
        buttonRoundness: "none",
        buttonColor: "#ffffff",
        buttonFontColor: "#ffffff",
        fontFamily: "monospace",
        fontColor: "#ffffff",
        preview: "bg-neutral-950",
        isPro: true,
    },
     {
        id: "graph-paper",
        name: "Graph Paper",
        category: "Graphics",
        type: "preset",
        bgType: "gradient",
        bgGradient: "bg-[#fff] bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:20px_20px]",
        buttonStyle: "hard-shadow",
        buttonRoundness: "none",
        buttonColor: "#ffffff",
        buttonFontColor: "#000000",
        fontFamily: "Inter",
        fontColor: "#000000",
        preview: "bg-white border",
        isPro: true,
    },
    {
        id: "checkerboard",
        name: "Checker",
        category: "Graphics",
        type: "preset",
        bgType: "gradient",
        bgGradient: "bg-[#f0f0f0] bg-[linear-gradient(45deg,#ccc_25%,transparent_25%,transparent_75%,#ccc_75%,#ccc),linear-gradient(45deg,#ccc_25%,transparent_25%,transparent_75%,#ccc_75%,#ccc)] bg-[size:20px_20px] bg-[position:0_0,10px_10px]",
        buttonStyle: "fill",
        buttonRoundness: "none",
        buttonColor: "#000000",
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#000000",
        preview: "bg-[#e5e5e5]",
        isPro: true,
    },
    {
        id: "circuit-board",
        name: "Circuit",
        category: "Graphics",
        type: "preset",
        bgType: "color",
        bgColor: "#1a1a1a",
        // Using image for complex pattern, or could use SVG
        bgImage: "https://www.transparenttextures.com/patterns/circuit-board.png", // Texture
        buttonStyle: "outline",
        buttonRoundness: "none",
        buttonColor: "#22c55e",
        buttonFontColor: "#22c55e",
        fontFamily: "monospace",
        fontColor: "#22c55e",
        preview: "bg-[#1a1a1a]",
        isPro: true,
    },
    {
        id: "diagonal-stripes",
        name: "Warning",
        category: "Graphics",
        type: "preset",
        bgType: "gradient",
        bgGradient: "bg-yellow-400 bg-[linear-gradient(45deg,#000_25%,transparent_25%,transparent_50%,#000_50%,#000_75%,transparent_75%,transparent)] bg-[size:40px_40px]",
        buttonStyle: "fill",
        buttonRoundness: "none",
        buttonColor: "#000000",
        buttonFontColor: "#fbbf24",
        fontFamily: "Inter",
        fontColor: "#000000",
        preview: "bg-yellow-400",
        isPro: true,
    },
    {
        id: "polka-dots",
        name: "Polka",
        category: "Graphics",
        type: "preset",
        bgType: "gradient",
        bgGradient: "bg-[#8b5cf6] bg-[radial-gradient(#ffffff44_3px,transparent_3px)] bg-[size:30px_30px]",
        buttonStyle: "fill",
        buttonRoundness: "full",
        buttonColor: "#ffffff",
        buttonFontColor: "#7c3aed",
        fontFamily: "Plus Jakarta Sans",
        fontColor: "#ffffff",
        preview: "bg-[#8b5cf6]",
        isPro: false, // Free
    },
    {
        id: "zigzag",
        name: "Zigzag",
        category: "Graphics",
        type: "preset",
        bgType: "gradient",
        bgGradient: "bg-[#ec4899] bg-[linear-gradient(135deg,#db2777_25%,transparent_25%),linear-gradient(225deg,#db2777_25%,transparent_25%),linear-gradient(45deg,#db2777_25%,transparent_25%),linear-gradient(315deg,#db2777_25%,transparent_25%)] bg-[size:40px_40px]",
        buttonStyle: "fill",
        buttonRoundness: "lg",
        buttonColor: "#ffffff",
        buttonFontColor: "#be185d",
        fontFamily: "Inter",
        fontColor: "#ffffff",
        preview: "bg-[#ec4899]",
        isPro: true,
    },
    {
        id: "hexagons",
        name: "Hexagons",
        category: "Graphics",
        type: "preset",
        bgType: "color",
        bgColor: "#111827",
        bgImage: "https://www.transparenttextures.com/patterns/cubes.png",
        buttonStyle: "outline",
        buttonRoundness: "md",
        buttonColor: "#60a5fa",
        buttonFontColor: "#60a5fa",
        fontFamily: "Inter",
        fontColor: "#93c5fd",
        preview: "bg-gray-900",
        isPro: true,
    },
    {
        id: "carbon-fiber",
        name: "Carbon",
        category: "Graphics",
        type: "preset",
        bgType: "color",
        bgColor: "#171717",
        bgImage: "https://www.transparenttextures.com/patterns/carbon-fibre.png",
        buttonStyle: "fill",
        buttonRoundness: "xl",
        buttonColor: "#262626",
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#d4d4d4",
        preview: "bg-[#171717]",
        isPro: true,
    },

    // ============================================
    // 4. DARK (10)
    // ============================================
    {
        id: "noir-luxury",
        name: "Noir",
        category: "Dark",
        type: "preset",
        bgType: "color",
        bgColor: "#000000",
        buttonStyle: "outline",
        buttonRoundness: "none",
        buttonColor: "#ffffff",
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#ffffff",
        preview: "bg-black",
        isPro: true,
    },
    {
        id: "gold-luxury",
        name: "Gold",
        category: "Dark",
        type: "preset",
        bgType: "color",
        bgColor: "#0f0f0f",
        buttonStyle: "outline",
        buttonRoundness: "none",
        buttonColor: "#D4AF37",
        buttonFontColor: "#D4AF37",
        fontFamily: "serif",
        fontColor: "#D4AF37",
        preview: "bg-neutral-900 border border-yellow-600",
        isPro: true,
    },
    {
        id: "midnight-blue",
        name: "Midnight",
        category: "Dark",
        type: "preset",
        bgType: "color",
        bgColor: "#1e1b4b", // indigo-950
        buttonStyle: "soft",
        buttonRoundness: "xl",
        buttonColor: "#312e81",
        buttonFontColor: "#c7d2fe",
        fontFamily: "Inter",
        fontColor: "#e0e7ff",
        preview: "bg-[#1e1b4b]",
        isPro: false,
    },
    {
        id: "forest-dark",
        name: "Deep Forest",
        category: "Dark",
        type: "preset",
        bgType: "color",
        bgColor: "#022c22", // emerald-950
        buttonStyle: "soft",
        buttonRoundness: "xl",
        buttonColor: "#064e3b",
        buttonFontColor: "#d1fae5",
        fontFamily: "Inter",
        fontColor: "#ecfdf5",
        preview: "bg-[#022c22]",
        isPro: false,
    },
    {
        id: "wine-dark",
        name: "Fine Wine",
        category: "Dark",
        type: "preset",
        bgType: "color",
        bgColor: "#450a0a", // red-950
        buttonStyle: "fill",
        buttonRoundness: "lg",
        buttonColor: "#7f1d1d",
        buttonFontColor: "#fecaca",
        fontFamily: "serif",
        fontColor: "#fee2e2",
        preview: "bg-[#450a0a]",
        isPro: true,
    },
    {
        id: "slate-dark",
        name: "Gunmetal",
        category: "Dark",
        type: "preset",
        bgType: "color",
        bgColor: "#0f172a", // slate-900
        buttonStyle: "fill",
        buttonRoundness: "md",
        buttonColor: "#334155",
        buttonFontColor: "#f1f5f9",
        fontFamily: "Inter",
        fontColor: "#cbd5e1",
        preview: "bg-[#0f172a]",
        isPro: false,
    },
    {
        id: "vampire",
        name: "Vampire",
        category: "Dark",
        type: "preset",
        bgType: "gradient",
        bgGradient: "bg-gradient-to-t from-black to-red-900",
        buttonStyle: "outline",
        buttonRoundness: "none",
        buttonColor: "#ef4444",
        buttonFontColor: "#fca5a5",
        fontFamily: "serif",
        fontColor: "#fee2e2",
        preview: "bg-gradient-to-t from-black to-red-900",
        isPro: true,
    },
    {
        id: "obsidian-glass",
        name: "Obsidian",
        category: "Dark",
        type: "preset",
        bgType: "color",
        bgColor: "#000000",
        buttonStyle: "soft",
        buttonRoundness: "2xl",
        buttonColor: "rgba(255,255,255,0.15)",
        buttonFontColor: "#ffffff",
        fontFamily: "Inter",
        fontColor: "#a3a3a3",
        preview: "bg-black",
        isPro: true,
    },
    {
        id: "cyber-neon",
        name: "Cyber",
        category: "Dark",
        type: "preset",
        bgType: "color",
        bgColor: "#050505",
        buttonStyle: "outline",
        buttonRoundness: "none",
        buttonColor: "#00ff9d",
        buttonFontColor: "#00ff9d",
        fontFamily: "monospace",
        fontColor: "#00ff9d",
        buttonStyle: "fill",
        buttonRoundness: "xl",
        buttonColor: "#ffffff",
        buttonFontColor: "#991b1b",
        fontFamily: "Inter",
        fontColor: "#ffffff",
        preview: "bg-[url('https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=500&auto=format&fit=crop')] bg-cover",
        isPro: true,
    },
];
